/* eslint-disable @typescript-eslint/no-unused-vars */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";

import { AuthProvider } from "./context/AuthContext";
import { Provider } from "react-redux";
import { store } from "./store/store";
import ReduxProvider from "./ReduxProvider";
import LocationProvider from "./LocationProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       

        <ReduxProvider>
         <div className="flex min-h-screen">
        <Sidebar/>
         
        <main className="flex-1 bg-gray-50">
         
        {children}
        </main>
       </div>
        </ReduxProvider>
       
      </body>
    </html>
  );
}
